### ISSUE TITLE
model convert unexpected

### ISSUE THREAD

**Issue by jinfagang** [pnnx/pnnx#62] opened 2022-11-08 05:59 UTC
```
class Model2(nn.Module):
    def __init__(self):
        super(Model2, self).__init__()

        # self.b = torch.randint(0, 23, [4, 3, 23])

    def forward(self, x):
        # x = x[:, 1]
        # x = x[..., :6]
        x[..., 0::3] = (x[..., ::3] * 2.)*32
        # x = x[:, :, 1:2]
        # x = x[0:2, 0:1, 1:]
        # x = x[0:2, 0:1]
        # x = x[0:2, 1:1]
        bs = x.shape[0]
        x = x.reshape(bs, -1, 6)
        return x
```

pnnx output:

```
7767517
3 2
pnnx.Input               pnnx_input_0             0 1 0 #0=(1,3,80,80,21)f32
Tensor.reshape           Tensor.reshape_0         1 1 0 1 shape=(1,-1,6) $input=0 #0=(1,3,80,80,21)f32 #1=(1,67200,6)f32
pnnx.Output              pnnx_output_0            1 0 1 #1=(1,67200,6)f32

```

PTAL

**Comment by nihui** [comment] 2022-11-08 11:10
duplicate of https://github.com/Tencent/ncnn/issues/4335

**Closed by nihui** 2022-11-08 11:10 UTC
