### ISSUE TITLE
layer nn.MultiheadAttention not exists or registered

### ISSUE THREAD

**Issue by serwansj** [pnnx/pnnx#83] opened 2023-05-26 14:56 UTC
Was trying to export a minimal example to NCNN through PNNX:

1. My PyTorch/Python code is the following:
```python
class Model(torch.nn.Module):

    def __init__(self):
        super().__init__()
        self.attn = torch.nn.MultiheadAttention(embed_dim=256, num_heads=8)

    def forward(self, x):
        return self.attn(x, x, x)


def run():

    model = Model()
    model.eval()
    x = torch.randn((10, 1, 256))
    mod = torch.jit.trace(model, x)
    mod.save('models/mha.pt')


if __name__ == '__main__':
    run()
```

2. I export to PNNX `./pnnx models/mha.pt inputshape=[10,1,256]` and get the following log:
```
pnnxparam = models/dummy.pnnx.param
pnnxbin = models/dummy.pnnx.bin
pnnxpy = models/dummy_pnnx.py
pnnxonnx = models/dummy.pnnx.onnx
ncnnparam = models/dummy.ncnn.param
ncnnbin = models/dummy.ncnn.bin
ncnnpy = models/dummy_ncnn.py
fp16 = 1
optlevel = 2
device = cpu
inputshape = [10,1,256]f32
inputshape2 = 
customop = 
moduleop = 
############# pass_level0

----------------

############# pass_level1
############# pass_level2
############# pass_level3
############# pass_level4
############# pass_level5
############# pass_ncnn
ignore nn.MultiheadAttention attn param add_bias_kv=False
ignore nn.MultiheadAttention attn param add_zero_attn=False
ignore nn.MultiheadAttention attn param batch_first=False
ignore nn.MultiheadAttention attn param bias=True
ignore nn.MultiheadAttention attn param embed_dim=256
ignore nn.MultiheadAttention attn param kdim=256
ignore nn.MultiheadAttention attn param num_heads=8
ignore nn.MultiheadAttention attn param vdim=256
```

3. Finally, I load the model in NCNN:
```cpp
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
#include "net.h"

int main()
{

    ncnn::Net net;
    net.load_param("models/mha.ncnn.param");
    net.load_model("models/mha.ncnn.bin");

    return 0;
}
```
and get the output
```
layer nn.MultiheadAttention not exists or registered
Segmentation fault (core dumped)
```

Would appreciate any help with this because I am struggling massively to export the MultiHeadAttention layer to NCNN.

**Comment by nihui** [comment] 2023-06-05 02:43
duplicate of https://github.com/Tencent/ncnn/issues/4756

**Closed by nihui** 2023-06-05 02:43 UTC
